//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WALLPOSTS
    {
        public int PID { get; set; }
        public int Poster { get; set; }
        public int Reciever { get; set; }
        public System.DateTime Time { get; set; }
        public string Content { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual USERS USERS1 { get; set; }
    }
}
